#!/usr/bin/env python3
"""
Generates supabase/seed.sql from the extract output CSV.
Filters to confidence >= 0.7, deduplicates by title, generates slugs,
appends UTM to visit_site_url, and outputs INSERT statements.

Usage:
  python3 supabase/generate_seed.py
"""

import csv, re, json, os

CSV_PATH = os.path.join(os.path.dirname(__file__), '../../jungle-summer-extract/output/results.csv')
OUT_PATH = os.path.join(os.path.dirname(__file__), 'seed.sql')

UTM = "utm_source=jungle&utm_medium=summer&utm_campaign=thing_to_do_{slug}"

def slugify(text):
    s = text.lower()
    s = re.sub(r'[^\w\s-]', '', s)
    s = re.sub(r'[\s_-]+', '-', s).strip('-')
    return s[:80]

def q(val):
    """Postgres single-quoted string, None → NULL."""
    if val is None or val == '':
        return 'NULL'
    return "'" + str(val).replace("'", "''") + "'"

def q_array(val):
    """Text[] literal from semicolon-separated string or list."""
    if not val:
        return "'{}'::text[]"
    if isinstance(val, str):
        items = [v.strip() for v in val.split(';') if v.strip()]
    else:
        items = list(val)
    if not items:
        return "'{}'::text[]"
    inner = ','.join("'" + i.replace("'", "''") + "'" for i in items)
    return f"ARRAY[{inner}]::text[]"

def q_bool(val):
    if val == '' or val is None:
        return 'NULL'
    if str(val).lower() in ('true', '1', 'yes'):
        return 'TRUE'
    if str(val).lower() in ('false', '0', 'no'):
        return 'FALSE'
    return 'NULL'

def q_num(val):
    if val == '' or val is None:
        return 'NULL'
    try:
        return str(float(val))
    except ValueError:
        return 'NULL'

def q_date(val):
    if not val or val.strip() == '':
        return 'NULL'
    return q(val.strip())

def q_enum(val, enum_values, default=None):
    if val and val.strip().lower() in enum_values:
        return q(val.strip().lower())
    if default:
        return q(default)
    return 'NULL'

rows = []
seen_slugs = set()
seen_titles = set()

with open(CSV_PATH, newline='', encoding='utf-8') as f:
    for row in csv.DictReader(f):
        score = float(row.get('confidence_score') or 0)
        if score < 0.7:
            continue
        title = row['title'].strip()
        if not title or title.lower() in seen_titles:
            continue
        seen_titles.add(title.lower())

        base_slug = slugify(title)
        slug = base_slug
        n = 2
        while slug in seen_slugs:
            slug = f"{base_slug}-{n}"
            n += 1
        seen_slugs.add(slug)

        provider_url = row.get('provider_url', '').strip()
        sep = '&' if '?' in provider_url else '?'
        utm_tag = UTM.format(slug=slug)
        visit_site_url = f"{provider_url}{sep}{utm_tag}" if provider_url else ''

        rows.append({
            'slug': slug,
            'title': title,
            'provider_name': row.get('provider_name', ''),
            'provider_url': provider_url,
            'description': row.get('description', ''),
            'long_description': row.get('description', ''),
            'type': row.get('type', ''),
            'categories': row.get('categories', ''),
            'price_type': row.get('price_type', ''),
            'price_min': row.get('price_min', ''),
            'price_max': row.get('price_max', ''),
            'price_display': row.get('price_display', ''),
            'age_min': row.get('age_min', ''),
            'age_max': row.get('age_max', ''),
            'age_band': row.get('age_band', ''),
            'area': row.get('area', ''),
            'venue_name': row.get('venue_name', ''),
            'venue_address': row.get('venue_address', ''),
            'start_date': row.get('start_date', ''),
            'end_date': row.get('end_date', ''),
            'recurrence': row.get('recurrence', ''),
            'booking_required': row.get('booking_required', ''),
            'indoor_outdoor': row.get('indoor_outdoor', ''),
            'hero_image_url': row.get('hero_image_url', ''),
            'source_name': row.get('source_name', ''),
            'source_url': row.get('source_url', ''),
            'visit_site_url': visit_site_url,
            'confidence_score': score,
        })

VALID_TYPES = {'festival', 'show', 'museum', 'outdoor', 'library', 'attraction', 'free_event'}
VALID_PRICE = {'free', 'paid', 'mixed'}
VALID_IO = {'indoor', 'outdoor', 'both'}

lines = ["-- Jungle Summer seed data — generated by generate_seed.py",
         f"-- {len(rows)} records (confidence >= 0.7, deduplicated)",
         "",
         "insert into things_to_do (",
         "  slug, title, provider_name, provider_url, description, long_description,",
         "  type, categories, price_type, price_min, price_max, price_display,",
         "  age_min, age_max, age_band, area, venue_name, venue_address,",
         "  start_date, end_date, recurrence, booking_required, indoor_outdoor,",
         "  hero_image_url, source_name, source_url, visit_site_url,",
         "  confidence_score, review_status, status",
         ") values"]

vals = []
for r in rows:
    v = (
        f"  ({q(r['slug'])}, {q(r['title'])}, {q(r['provider_name'])}, {q(r['provider_url'])}, "
        f"{q(r['description'])}, {q(r['long_description'])},\n"
        f"   {q_enum(r['type'], VALID_TYPES)}, {q_array(r['categories'])}, "
        f"{q_enum(r['price_type'], VALID_PRICE)}, {q_num(r['price_min'])}, {q_num(r['price_max'])}, {q(r['price_display'])},\n"
        f"   {q_num(r['age_min'])}, {q_num(r['age_max'])}, {q_array(r['age_band'])}, "
        f"{q(r['area'])}, {q(r['venue_name'])}, {q(r['venue_address'])},\n"
        f"   {q_date(r['start_date'])}, {q_date(r['end_date'])}, {q(r['recurrence'])}, "
        f"{q_bool(r['booking_required'])}, {q_enum(r['indoor_outdoor'], VALID_IO)},\n"
        f"   {q(r['hero_image_url'])}, {q(r['source_name'])}, {q(r['source_url'])}, {q(r['visit_site_url'])},\n"
        f"   {r['confidence_score']}, 'needs_review', 'draft')"
    )
    vals.append(v)

lines.append(',\n'.join(vals) + ';')
lines.append("")
lines.append("-- After reviewing in Supabase Studio, run this to publish high-confidence records:")
lines.append("-- update things_to_do set review_status = 'approved', status = 'active'")
lines.append("-- where confidence_score >= 0.85 and review_status = 'needs_review';")

with open(OUT_PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Written {len(rows)} records to {OUT_PATH}")
